export const TREEDATA = [
  {
    name: 'Belgium - Challenger Pro League',
    children: [{ id: 1, name: 'Lommel SK v K Beerschot VA' }],
  },
  {
    name: 'Brazil - Paulista, Serie A2',
    children: [{ id: 2, name: 'Comercial FC SP v EC Prima vera SP' }],
  },
  {
    name: 'Englan - FA Cup',
    children: [
      { id: 3, name: 'Coventry City v Sheffield Wednesday' },
      { id: 4, name: 'Plymouth Argyle v Leeds United' },
    ],
  },
];

export const MATCHDATA = [
  {
    id: 1,
    team1: 'Lommel SK',
    team2: 'K Beerschot VA',
    data: [
      {
        option: '1X2',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 2000,
        sinRisk: null,
        sinBet: 3,
        stake: 307,
        pandl: 140,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Home',
        radar: 1.85,
        falcon: 2.5,
        sinLimit: 896,
        progress: 1000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Draw',
        radar: 59.69,
        falcon: 49.33,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 307,
        pandl: 140,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Away',
        radar: 1.85,
        falcon: 2.5,
        sinLimit: 9748,
        progress: 50000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Under Over +1.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 364,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 3256,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 8469,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Under Over +2.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
    ],
  },
  {
    id: 2,
    team1: 'Comercial FC SP',
    team2: 'EC Prima vera SP',
    data: [
      {
        option: "1X2",
        radar: 156.23,
        falcon: 65.49,
        sinLimit: 4827,
        progress: 18372,
        sinRisk: 2,
        sinBet: 7,
        stake: 254,
        pandl: 47,
        multiRisk: 893,
        head: true
      },
      {
        option: 'Home',
        radar: 43,
        falcon: 64,
        sinLimit: 3453,
        progress: 4000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Draw',
        radar: 345.69,
        falcon: 345.33,
        sinLimit: 453,
        progress: 5000,
        sinRisk: null,
        sinBet: 3,
        stake: 307,
        pandl: 140,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Away',
        radar: 143,
        falcon: 45,
        sinLimit: 3453,
        progress: 50000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Under Over +1.5',
        radar: 3453,
        falcon: 45.6,
        sinLimit: 3453,
        progress: 5000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 1345,
        falcon: 34,
        sinLimit: 3451,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 564,
        falcon: 744,
        sinLimit: 456,
        progress: 8778,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Under Over +2.5',
        radar: 3445,
        falcon: 8456,
        sinLimit: 45,
        progress: 675,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 345.15,
        falcon: 87.456,
        sinLimit: 45,
        progress: 4444,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 456.15,
        falcon: 87.74,
        sinLimit: 437,
        progress: 34563,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
    ],
  },
  {
    id: 3,
    team1: 'Coventry City',
    team2: 'Sheffield Wednesday',
    data: [
      {
        option: "1X2",
        radar: 563.22,
        falcon: 22.39,
        sinLimit: 345,
        progress: 7345,
        sinRisk: 5,
        sinBet: 2,
        stake: 488,
        pandl: 189,
        multiRisk: 243,
        head: true
      },
      {
        option: 'Home',
        radar: 1.4563,
        falcon: 2.456,
        sinLimit: 3456,
        progress: 6000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Draw',
        radar: 365,
        falcon: 49.34,
        sinLimit: 2345,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 307,
        pandl: 140,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Away',
        radar: 1.85,
        falcon: 2.5,
        sinLimit: 9748,
        progress: 50000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Under Over +1.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 364,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 3256,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 8469,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Under Over +2.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
    ],
  },
  {
    id: 4,
    team1: 'Plymouth Argyle',
    team2: 'Leeds United',
    data: [
      {
        option: "1X2",
        radar: 121.31,
        falcon: 66.17,
        sinLimit: 966,
        progress: 44230,
        sinRisk: 5,
        sinBet: 8,
        stake: 231,
        pandl: 148,
        multiRisk: 335,
        head: true
      },
      {
        option: 'Home',
        radar: 1.85,
        falcon: 2.5,
        sinLimit: 896,
        progress: 1000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Draw',
        radar: 59.69,
        falcon: 49.33,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 307,
        pandl: 140,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Away',
        radar: 1.85,
        falcon: 2.5,
        sinLimit: 9748,
        progress: 50000,
        sinRisk: 0,
        sinBet: 1,
        stake: 88,
        pandl: 0,
        multiRisk: '702[1]',
        head: false
      },
      {
        option: 'Under Over +1.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 364,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 3256,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 8469,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Under Over +2.5',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: true
      },
      {
        option: 'Under',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
      {
        option: 'Over',
        radar: 108.15,
        falcon: 87.78,
        sinLimit: 587,
        progress: 50000,
        sinRisk: null,
        sinBet: 3,
        stake: 0,
        pandl: 0,
        multiRisk: 702,
        head: false
      },
    ],
  },
];
